version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  test_client:
    build:
      context: .
      dockerfile: Dockerfile.test_client
    depends_on:
      web:
        condition: service_healthy
    environment:
      - API_URL=http://web:8080

volumes:
  postgres_data: